# Generated by Django 2.2.4 on 2019-09-14 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_posts', '0002_auto_20190909_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='this-is-the-slug'),
        ),
    ]
