# Generated by Django 2.2.4 on 2019-09-16 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_posts', '0005_auto_20190914_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='slug', unique=True),
        ),
    ]
