# Generated by Django 2.2.4 on 2019-11-07 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_posts', '0008_auto_20191007_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='desc',
            field=models.TextField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='thumb',
            field=models.ImageField(default='https://www.sciencenews.org/wp-content/uploads/2019/02/022119_EC_expanding-universe_feat.jpg', null=True, upload_to=''),
        ),
    ]
