# Generated by Django 2.2.4 on 2019-11-07 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_posts', '0013_auto_20191107_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField(default='World', max_length=100, null=True)),
            ],
        ),
    ]
