# Generated by Django 3.0.3 on 2020-03-06 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_posts', '0023_auto_20200302_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumb',
            field=models.URLField(max_length=1000, null=True),
        ),
    ]
