# Generated by Django 2.2.4 on 2019-11-05 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_reset_url_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='reset_url',
            name='username',
            field=models.CharField(default='erenaykaracan', max_length=150),
        ),
    ]
