# Generated by Django 2.2.4 on 2020-02-20 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_back'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Back',
        ),
    ]
