# Generated by Django 3.0.3 on 2020-03-06 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200303_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='prof',
            field=models.ImageField(default='/media/monet.jpg', upload_to='prof/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='member',
            name='wall',
            field=models.ImageField(default='/media/impression.jpg', upload_to='wall/%Y/%m/%d'),
        ),
    ]
