# Generated by Django 3.0.3 on 2020-03-06 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200306_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='prof',
            field=models.ImageField(default='/media/monet.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='member',
            name='wall',
            field=models.ImageField(default='/media/impression.jpg', upload_to=''),
        ),
    ]
