# Generated by Django 3.0.3 on 2020-03-07 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20200306_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='prof',
            field=models.ImageField(default='https://blogworld-storage.s3.eu-central-1.amazonaws.com/static/monet.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='member',
            name='wall',
            field=models.ImageField(default='https://blogworld-storage.s3.eu-central-1.amazonaws.com/static/impression.jpg', upload_to=''),
        ),
    ]
